### ISSUE TITLE
Implement theme prop for source-react-component components

### ISSUE THREAD

**Issue by oliverabrahams** [guardian/csnx#1087]
We are updating the implementation of themes in Source React components from a request for a [new dark mode for DCAR](https://github.com/guardian/dotcom-rendering/issues/9277). This involves a few changes to the way themes are handled in our Source React components: 
- Add theme prop with new theme object. 
- Create the new object with property names from [figma](https://www.figma.com/file/wQEC3OHlazYJMk1xdCnVsr/Component-variations-for-CSTI?type=design&node-id=0-1&mode=design&t=9XzDkZ4YcfLoKCBU-0). 
- Deprecate old theme for components.

```[tasklist]
### Tasks
- [x] https://github.com/guardian/csnx/issues/1125
- [ ] https://github.com/guardian/csnx/issues/1140
- [ ] https://github.com/guardian/csnx/issues/1124
- [ ] https://github.com/guardian/csnx/issues/1138
- [x] https://github.com/guardian/csnx/issues/1139
- [ ] https://github.com/guardian/csnx/issues/1142
- [ ] https://github.com/guardian/csnx/issues/1143
- [ ] https://github.com/guardian/csnx/issues/1144
- [ ] https://github.com/guardian/csnx/issues/1145
- [ ] https://github.com/guardian/csnx/issues/1136
- [ ] https://github.com/guardian/csnx/issues/1148
- [ ] https://github.com/guardian/csnx/issues/1154
- [x] https://github.com/guardian/csnx/issues/1159
- [x] https://github.com/guardian/csnx/issues/1160
- [x] https://github.com/guardian/csnx/issues/1161
- [ ] https://github.com/guardian/csnx/issues/1158
- [ ] https://github.com/guardian/csnx/issues/1176
- [ ] https://github.com/guardian/csnx/issues/1166
```
