### ISSUE TITLE
Transition from Nx to `wireit`

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#1310]
Nx does a lot more than we need it for, and there's a feeling that this is weighing down on maintenance and cognitive load for new devs.

[Wireit](https://github.com/google/wireit) provides a much lighter-weight option for defining cross-task dependency and output caching – the two things we use Nx for.

We will try incrementally swapping out Nx for wireit in the various corners of the repo, starting with the lowest impact areas (e.g. github pages) and working up the biggest (e.g. publishing source).

This way, if it works well, we'll end up removing Nx as we see the benefit. If it doesn't, we can revert the changes.

### Using Nx to run repo-wide tasks, for now

Because Nx will try to run matching `npm-scripts` if it can't find a task in the Nx `project.json`, we can keep using Nx to run the new wireit tasks while Nx is still set up to handle repo-wide tasks _and_ some project-specific tasks.

_For example, once `github-pages` is using wireit, running `make github-pages:build` can still call `pnpm nx run github-pages:build`. Since there's no actual `build` task in the project.json, Nx itself will run `pnpm build` in the `github-pages` project dir (starting the wireit task)._

This reduces the amount of change we need to make each time while making it easier to revert to full Nx if we need to.

If/when we decide to remove Nx, updating everything to run the npm-scripts directly will be the last step.

> [!TIP]
> Use a `W!RE!T` comment to leave inline instructions along the way that will help with any final switch over, e.g.
> ```js
> // W!RE!T
> // 1. remove the next line 
> const someNxConfig = {}
> // 2. uncomment this line
> // const someWireitConfig = {}
> ```
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/csnx/pull/1273
- [ ] https://github.com/guardian/csnx/pull/1317
- [ ] https://github.com/guardian/csnx/pull/1334
```
