### ISSUE TITLE
Move CMP to `@guardian/libs`

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#1326]
We want to add consent-based purpose checks to exports of `@guardian/libs` that write to user's devices (cookies, storage etc).

Because the CMP already depends on `libs`, consuming the CMP from `libs` would create [a circular dependency](https://dev.to/successgilli/circular-dependency-in-nodejs-and-nestjs-3e1d), which makes it impossible to manage updates etc.

Therefore, we need to co-locate this code.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/csnx/issues/1327
- [ ] https://github.com/guardian/csnx/issues/1328
- [x] Merge https://github.com/guardian/csnx/pull/1128
- [x] Upgrade consumers of CMP to `@guardian/libs`
- [ ] https://github.com/guardian/csnx/issues/1395
```
