### ISSUE TITLE
Build packages to a local `dist`

### ISSUE THREAD

**Issue by sndrs** [guardian/csnx#1420]
```[tasklist]
### Tasks
- [ ] update Nx config to build to local `dist`
- [ ] update changesets to use local `dist`
- [ ] remove paths/alisases from `tsconfig.base.json`, vite config in github pages and `nxPreset` in `configs/jest.config.ts` (and check for others)
- [ ] update `package.json`s to handle the stuff the current pipeline adds in build
```
