### ISSUE TITLE
Improve/fix Grafana dashboard output for tracker-source-usage lambda

### ISSUE THREAD

**Issue by tjsilver** [guardian/csnx#226]
- [ ] Releases section: investigate why there is nothing showing - no releases in time period? What is time period?
- [ ] Pull Requests section: fix Open Pull Requests split by contributor group
- [ ] Pull Requests section: fix Pull Requests split by contributor group
- [ ] Pull Requests section: investigate if there are issues with Pull Requests Opened (and how this data differs from 'Open Pull Requests'
- [ ] Pull Requests section: investigate if there are issues with Pull Requests Merged
- [ ] Pull Requests section: investigate if there are issues with Pull Requests Closed
- [ ] Issues section: fix 'Open Issues split by contributor group' (currently empty even though 18 open issues)
- [ ] Issues sectionl: fix 'Issues Opened split by contributor group', if necessary (no Issues Opened at time of writing)
- [ ] Contributions section: fix 'no data' for CSTI contributions (issue with CSTI contributor group?)
- [ ] Rename all refs to 'CSIT' to 'CSTI' (how to edit panels?)
